# Generated by Django 2.0.4 on 2018-05-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180502_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freeze_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
