# Generated by Django 2.0.4 on 2018-05-14 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='transaction_code',
            field=models.CharField(default=datetime.datetime(2018, 5, 14, 11, 51, 44, 429802, tzinfo=utc), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
